spring.application.name=money-pilot
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=com.example.moneyPilot.mybatis

app.jwt.issuer=money-pilot
app.jwt.access-token-expiration-seconds=3600
app.jwt.refresh-token-expiration-seconds=2592000
app.jwt.secret=change-this-secret-key-to-32chars-minimum-123456
